# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.27
# 

Name:       ownNotes

# >> macros
# << macros

%{!?qtc_qmake:%define qtc_qmake %qmake}
%{!?qtc_qmake5:%define qtc_qmake5 %qmake5}
%{!?qtc_make:%define qtc_make make}
%{?qtc_builddir:%define _builddir %qtc_builddir}
Summary:    A notes taking app with ownCloud Sync
Version:    1.5.2
Release:    1
Group:      Qt/Qt
License:    LICENSE
URL:        http://example.org/
Source0:    %{name}-%{version}.tar.bz2
Source100:  ownNotes.yaml
Requires:   sailfishsilica-qt5 >= 0.10.9
Requires:   python3-base
BuildRequires:  pkgconfig(Qt5Quick)
BuildRequires:  pkgconfig(Qt5Qml)
BuildRequires:  pkgconfig(Qt5Core)
BuildRequires:  pkgconfig(sailfishapp) >= 0.0.10
BuildRequires:  pkgconfig(Qt5Widgets)
BuildRequires:  python3-devel
BuildRequires:  desktop-file-utils

%description
A notes taking app with ownCloud Sync and markdown support.

%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
# << build pre

%qtc_qmake5 

%qtc_make %{?_smp_mflags}

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%qmake5_install

# >> install post
# << install post

desktop-file-install --delete-original       \
  --dir %{buildroot}%{_datadir}/applications             \
   %{buildroot}%{_datadir}/applications/*.desktop

%files
%defattr(755,root,root,755)
%{_datadir}/%{name}/python
%{_datadir}/%{name}/qml
%{_datadir}/%{name}/i18n
%{_datadir}/%{name}/datas
%{_datadir}/%{name}/icons
%{_datadir}/applications/%{name}.desktop
%{_datadir}/icons/hicolor/86x86/apps/%{name}.png
/usr/share/applications
/usr/share/icons/hicolor/86x86/apps
%attr(755,root,root) %{_bindir}
# >> files
# << files
